exclude: 'docs|node_modules|.git|.tox|.idea|.pytest_cache'
default_stages: [commit]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--line-length=180]

  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check
        args: ["--ignore=51377,51378,51379,51374,50814,50815,50816,50817,50768,50818,53269,51457"]
